{{- if .Values.kafka.enabled }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.kafka.syncWave }}"
spec:
  replicas: {{ .Values.kafka.brokerReplicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage }}
        deleteClaim: false
{{- end }}
