{{- if .Values.paymentsPostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: payments-db-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.paymentsPostgres.syncWave }}"
type: Opaque
stringData:
  DB_USERNAME: "{{ .Values.paymentsPostgres.username }}"
  DB_PASSWORD: "{{ .Values.paymentsPostgres.password }}"
{{- end }}
