{{- if .Values.ordersMysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.ordersMysql.syncWave }}"
type: Opaque
stringData:
  DB_USERNAME: "{{ .Values.ordersMysql.username }}"
  DB_PASSWORD: "{{ .Values.ordersMysql.password }}"
  DB_ROOT_PASSWORD: "{{ .Values.ordersMysql.rootPassword }}"
{{- end }}
