{{- if .Values.ordersMysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orders-mysql
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.ordersMysql.syncWave }}"
spec:
  type: ClusterIP
  selector:
    app: orders-mysql
  ports:
    - port: {{ .Values.ordersMysql.port }}
      targetPort: {{ .Values.ordersMysql.port }}
{{- end }}
