apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 200Mi
        deleteClaim: false

---

apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: order-events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  partitions: 1
  replicas: 1
  config:
    min.insync.replicas: 1
    cleanup.policy: delete

---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      # Disable auto topic creation to ensure topics are created with the correct configuration via Topic Operators
      auto.create.topics.enable: false

      # Single-node settings
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: { }
    userOperator: { }
