spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cloud:
    function:
      definition: orderEventDeserializer|paymentReservationProcessor|paymentEventSerializer

    stream:
      function:
        bindings:
          orderEventDeserializerpaymentReservationProcessorpaymentEventSerializer-in-0: order-events-input
          orderEventDeserializerpaymentReservationProcessorpaymentEventSerializer-out-0: payment-events-output

      bindings:
        order-events-input:
          destination: order-events-functions
          content-type: application/octet-stream
          group: functions-payment-group
          consumer:
            max-attempts: 3
            concurrency: 3
        payment-events-output:
          destination: payment-events-functions
          content-type: application/octet-stream

      kafka:
        binder:
          brokers: kafka-kafka-bootstrap.kafka:9092
          auto-create-topics: false
          required-acks: all
          replication-factor: 1
          min-partition-count: 3
          configuration:
            min.insync.replicas: 1
          consumer-properties:
            auto.offset.reset: latest
        bindings:
          orderEventDeserializerpaymentReservationProcessorpaymentEventSerializer-in-0:
            consumer:
              enable-dlq: true
              dlq-name: order-events-functions-dlq

server:
  port: 8080

app:
  kafka:
    enabled: true
