apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outbox-k8s-demo
spec:
  destination:
    namespace: demo-k8s
    server: https://kubernetes.default.svc
  source:
    path: k8s-v3
    repoURL: https://github.com/EugeneIsHere14/outbox-k8s-demo.git
    targetRevision: feature/helm-migration
    helm:
      releaseName: outbox-k8s-demo
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - ApplyOutOfSyncOnly=true
