{{- if .Values.customersSnapshotConnector.enabled }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: customers-snapshot-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.customersSnapshotConnector.syncWave }}"
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: "{{ .Values.debeziumConnector.ordersDatabaseHost }}"
    database.port: "{{ .Values.debeziumConnector.ordersDatabasePort }}"
    database.user: "{{ .Values.debeziumConnector.ordersDatabaseUser }}"
    database.password: "{{ .Values.debeziumConnector.ordersDatabasePassword }}"
    database.server.id: "{{ .Values.customersSnapshotConnector.serverId }}"
    topic.prefix: "{{ .Values.customersSnapshotConnector.topicPrefix }}"
    database.include.list: "orders"
    table.include.list: "orders.customers_snapshot_test,orders.debezium_signals"
    schema.history.internal.kafka.bootstrap.servers: "kafka-kafka-bootstrap:9092"
    schema.history.internal.kafka.topic: "schemahistory.customers-snapshot"
    include.schema.changes: "false"
    snapshot.mode: "{{ .Values.customersSnapshotConnector.snapshotMode }}"
    signal.enabled.channels: "source"
    signal.data.collection: "orders.debezium_signals"
    incremental.snapshot.chunk.size: "{{ .Values.customersSnapshotConnector.incrementalSnapshotChunkSize }}"
    tombstones.on.delete: "false"
{{- end }}
